trainer: {
lr: 0.00001,
record: True,
epochs: 25000,
epochs_callback: 5,
steps_callback: 1000,
scheduler: "warmup",
num_warmup_steps: 10000,
ddp: False,
deepspeed: False,
use_quartet_loss: True,
use_mlm_loss: False,
resume: False,
symmetry_loss: 1,
save_path: "Phyla/phyla/checkpoints/",
model_type: "Phyla-beta",
#model_type: "ESM2",
run_name: "test",
checkpoint_path: None,
val_callback_freq: 50
} 

dataset: {
#dataset: "GTB",
#dataset: 'GTB'
dataset_directories: ["yektefaie/Cleaned_Open_Protein_Set"],
dataset_size: None,
max_subtree_size_scaler: 1.0,
# dataset: "protein_gym"
}

model: {
  d_model: 256,
  n_layer: 16,
  vocab_size: 29,
  ssm_cfg: {},
  rms_norm: True,
  residual_in_fp32: True,
  fused_add_norm: True,
  pad_vocab_size_multiple: 8,
  num_blocks: 10,
  model_name: 'Phyla-beta',
  calculation_method: "attention",
  inject_rotary_attention: False,
  positional_embeddings: False,
  bidirectional: True,
  bidirectional_strategy: "add",
  bidirectional_weight_tie: True,
  ranking_loss: False
}
